### ISSUE TITLE
当系统环境变量中存在远古版本的adb时，questpatcher会直接报错、无法运行

### ISSUE THREAD

**Issue by WGzeyu** [MicroCBer/QuestPatcher#13]

**Comment by MicroCBer** [comment]
已经有版本检测了，[#39d1b08](https://github.com/MicroCBer/QuestPatcher/commit/39d1b08f564724119550d5ea6830038b7b561f8a)

**Comment by WGzeyu** [comment]
> 已经有版本检测了，[#39d1b08](https://github.com/MicroCBer/QuestPatcher/commit/39d1b08f564724119550d5ea6830038b7b561f8a)

并没有解决问题，直到最新的那个release都有人复现该情况，我远程确认过，删掉环境变量就好了

**Comment by WGzeyu** [comment]
> 已经有版本检测了，[#39d1b08](https://github.com/MicroCBer/QuestPatcher/commit/39d1b08f564724119550d5ea6830038b7b561f8a)

那个用户的adb程序打包以及存放路径、环境变量截图在群里都有，你可以试试

**Comment by MicroCBer** [comment]
之前没输出日志，现在加了，下次遇到再看

**Comment by WGzeyu** [comment]
> 之前没输出日志，现在加了，下次遇到再看

直接用我提供的那些文件，就能复现了：
```
[2022-11-04 18:33:20 DBG] Saving default config file . . .
[2022-11-04 18:33:20 INF] Loading config . . .
[2022-11-04 18:33:21 DBG] QuestPatcherService constructed (QuestPatcher version 2.4.302)
[2022-11-04 18:33:21 DBG] Loading default themes
[2022-11-04 18:33:21 DBG] 2 themes loaded successfully!
[2022-11-04 18:33:23 INF] Starting QuestPatcher . . .
[2022-11-04 18:33:23 DBG] Executing ADB command: adb shell "pm list packages com.beatgames.beatsaber"
[2022-11-04 18:33:33 ERR] Exiting QuestPatcher due to unhandled load error: System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at QuestPatcher.Core.ProcessUtil.InvokeAndCaptureOutput(String fileName, String arguments) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\ProcessUtil.cs:line 71
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 154
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 221
   at QuestPatcher.Core.AndroidDebugBridge.IsPackageInstalled(String packageId) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 250
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 114
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 94
[2022-11-04 18:33:33 DBG] Closing QuestPatcher . . .
[2022-11-04 18:33:33 INF] Saving config file . . .
[2022-11-04 18:33:33 DBG] Goodbye!

```

**Comment by MicroCBer** [comment]
已修复（[808daa9](https://github.com/MicroCBer/QuestPatcher/commit/808daa92d4660c6e2d1da82aecf87fc63f29a31a)）
